export type DetailOptionIcon = 'sparkles';

export interface DetailOptionData {
    label: string;
    images: string[];
    icon?: DetailOptionIcon;
    isActive?: boolean;
}

export interface CarData {
    id: string;
    name: string;
    year: number;
    price: string;
    image: string; // primary image used across the app
    detailOptions: DetailOptionData[];
    fuelType: string;
    transmission: string;
    kmsDriven: string;
    location: string;
    owner: string;
    registrationYear: string;
    insurance: string;
    seats: string;
    rto: string;
    engineDisplacement: string;
    yearOfManufacture: string;
    emi?: string;
    newCarPrice?: string;
    views?: string;
    badgeType: 'assured' | 'private'; // 'assured' for LINK DRIVE Assured, 'private' for Private Seller
}

export const sampleCars: CarData[] = [
    {
        id: "1",
        name: "Maruti Swift ZXI CNG",
        year: 2023,
        price: "₹5.57 lakh",
        image: "/car/MarutiSwift/MarutiSwift.png",
        detailOptions: [
            {
                label: 'Exterior',
                images: [
                    '/car/MarutiSwift/Exterior/Exterior1.png',
                    '/car/MarutiSwift/Exterior/Exterior2.png',
                    '/car/MarutiSwift/Exterior/Exterior3.png',
                    '/car/MarutiSwift/Exterior/Exterior4.png',
                    '/car/MarutiSwift/Exterior/Exterior5.png',
                    '/car/MarutiSwift/Exterior/Exterior6.png',
                    '/car/MarutiSwift/Exterior/Exterior7.png',
                    '/car/MarutiSwift/Exterior/Exterior8.png',
                    '/car/MarutiSwift/Exterior/Exterior9.png',
                ],
                isActive: true
            },
            {
                label: 'Interior',
                images: [
                    '/car/MarutiSwift/Interior/Interior1.png',
                    '/car/MarutiSwift/Interior/Interior2.jpeg',
                    '/car/MarutiSwift/Interior/Interior3.jpeg',
                    '/car/MarutiSwift/Interior/Interior4.png',
                    '/car/MarutiSwift/Interior/Interior5.jpeg',
                ],
            },
            // { label: 'Highlights', images: ['/car/car2.png', '/car/car4.png'], icon: 'sparkles' },
            {
                label: 'Tyres',
                images: [
                    '/car/MarutiSwift/Tyres/Tyres1.jpeg',
                    '/car/MarutiSwift/Tyres/Tyres2.jpeg',
                    '/car/MarutiSwift/Tyres/Tyres3.jpeg',
                    '/car/MarutiSwift/Tyres/Tyres4.jpeg',
                    '/car/MarutiSwift/Tyres/Tyres5.jpeg',
                ],
            },
        ],
        fuelType: "CNG",
        transmission: "Manual",
        kmsDriven: "52,519 km",
        location: "G.I.P.C.L., Surat",
        owner: "First Owner",
        registrationYear: "2023",
        insurance: "Valid till Feb 2026",
        seats: "5 Seats",
        rto: "Bardoli",
        engineDisplacement: "1197 cc",
        yearOfManufacture: "2023",
        emi: "₹18,616 /mo",
        newCarPrice: "₹8.57 Lakh",
        views: "1,100+",
        badgeType: "assured",
    },
    {
        id: "2",
        name: "Hyundai i20 SPORTZ 1.2",
        year: 2011,
        price: "₹2.15 Lakh",
        image: "/car/i20/i20.png",
        detailOptions: [
            { 
                label: 'Exterior',
                images: [
                    '/car/i20/Exterior/Exterior1.jpeg',
                    '/car/i20/Exterior/Exterior2.jpeg',
                    '/car/i20/Exterior/Exterior3.jpeg',
                    '/car/i20/Exterior/Exterior4.jpeg',
                    '/car/i20/Exterior/Exterior5.jpeg',
                    '/car/i20/Exterior/Exterior6.jpeg',
                    '/car/i20/Exterior/Exterior7.jpeg',
                    '/car/i20/Exterior/Exterior8.jpeg',
                    '/car/i20/Exterior/Exterior9.jpeg',
                    '/car/i20/Exterior/Exterior10.jpeg',
                    '/car/i20/Exterior/Exterior11.jpeg',
                    '/car/i20/Exterior/Exterior12.jpeg',
                    '/car/i20/Exterior/Exterior13.jpeg',
                ],
                isActive: true
            },
            {
                label: 'Interior',
                images: [
                    '/car/i20/Interior/Interior1.jpeg',
                    '/car/i20/Interior/Interior2.jpeg',
                    '/car/i20/Interior/Interior3.jpeg',
                    '/car/i20/Interior/Interior4.jpeg',
                ],
            },
            // { label: 'Highlights', images: ['/car/car3.png', '/car/car5.png'], icon: 'sparkles' },
            { label: 'Tyres',
                 images: [
                    '/car/i20/Tyre/Tyres1.jpeg',
                    '/car/i20/Tyre/Tyres2.jpeg',
                    '/car/i20/Tyre/Tyres3.jpeg',
                    '/car/i20/Tyre/Tyres4.jpeg',
                    '/car/i20/Tyre/Tyres5.jpeg',
                ],
            },
        ],
        fuelType: "Diesel",
        transmission: "Manual",
        kmsDriven: "1,25,500 Kms",
        location: "Surat, Gujarat",
        owner: "Third Owner",
        registrationYear: "2011",
        insurance: "Not Available",
        seats: "5 Seats",
        rto: "Surat",
        engineDisplacement: "1197 cc",
        yearOfManufacture: "2011",
        emi: "₹18,616 /mo",
        newCarPrice: "₹6.15 Lakh",
        views: "1,100+",
        badgeType: "private",
    },
    {
        id: "3",
        name: "Toyota Prius",
        year: 2023,
        price: "₹15.75 Lakh",
        image: "/car/car3.png",
        detailOptions: [
            { label: 'Exterior', images: ['/car/car3.png', '/car/car4.png'], isActive: true },
            { label: 'Interior', images: ['/car/car5.png', '/car/car6.png'] },
            // { label: 'Highlights', images: ['/car/car4.png', '/car/car6.png'], icon: 'sparkles' },
            { label: 'Tyres', images: ['/car/car5.png', '/car/car3.png'] },
        ],
        fuelType: "Hybrid",
        transmission: "Automatic",
        kmsDriven: "18,000 Kms",
        location: "Connaught Place, Delhi",
        owner: "First Owner",
        registrationYear: "2023",
        insurance: "Valid till Jun 2025",
        seats: "5 Seats",
        rto: "Delhi",
        engineDisplacement: "1798 cc",
        yearOfManufacture: "2023",
        emi: "₹39,000 /mo",
        newCarPrice: "₹18.50 Lakh",
        views: "4200+",
        badgeType: "assured",
    },
    {
        id: "4",
        name: "Kia Niro EV",
        year: 2022,
        price: "₹18.20 Lakh",
        image: "/car/car4.png",
        detailOptions: [
            { label: 'Exterior', images: ['/car/car4.png', '/car/car5.png'], isActive: true },
            { label: 'Interior', images: ['/car/car6.png', '/car/car7.png'] },
            // { label: 'Highlights', images: ['/car/car5.png', '/car/car7.png'], icon: 'sparkles' },
            { label: 'Tyres', images: ['/car/car6.png', '/car/car4.png'] },
        ],
        fuelType: "Electric",
        transmission: "Automatic",
        kmsDriven: "22,000 Kms",
        location: "Koramangala, Bangalore",
        owner: "Second Owner",
        registrationYear: "2022",
        insurance: "Valid till Sep 2024",
        seats: "5 Seats",
        rto: "Bangalore",
        engineDisplacement: "Electric Motor",
        yearOfManufacture: "2022",
        emi: "₹45,000 /mo",
        newCarPrice: "₹22.00 Lakh",
        views: "3500+",
        badgeType: "private",
    },
    {
        id: "5",
        name: "VW ID",
        year: 2021,
        price: "₹16.50 Lakh",
        image: "/car/car5.png",
        detailOptions: [
            { label: 'Exterior', images: ['/car/car5.png', '/car/car6.png'], isActive: true },
            { label: 'Interior', images: ['/car/car7.png', '/car/car8.png'] },
            // { label: 'Highlights', images: ['/car/car6.png', '/car/car8.png'], icon: 'sparkles' },
            { label: 'Tyres', images: ['/car/car7.png', '/car/car5.png'] },
        ],
        fuelType: "Electric",
        transmission: "Automatic",
        kmsDriven: "30,000 Kms",
        location: "Hinjewadi, Pune",
        owner: "First Owner",
        registrationYear: "2021",
        insurance: "Valid till Dec 2024",
        seats: "5 Seats",
        rto: "Pune",
        engineDisplacement: "Electric Motor",
        yearOfManufacture: "2021",
        emi: "₹41,000 /mo",
        newCarPrice: "₹20.00 Lakh",
        views: "2900+",
        badgeType: "assured",
    },
    {
        id: "6",
        name: "Honda City",
        year: 2023,
        price: "₹11.25 Lakh",
        image: "/car/car6.png",
        detailOptions: [
            { label: 'Exterior', images: ['/car/car6.png', '/car/car7.png'], isActive: true },
            { label: 'Interior', images: ['/car/car8.png', '/car/car9.png'] },
            // { label: 'Highlights', images: ['/car/car7.png', '/car/car9.png'], icon: 'sparkles' },
            { label: 'Tyres', images: ['/car/car8.png', '/car/car6.png'] },
        ],
        fuelType: "Petrol",
        transmission: "Manual",
        kmsDriven: "15,000 Kms",
        location: "Navrangpura, Ahmedabad",
        owner: "First Owner",
        registrationYear: "2023",
        insurance: "Valid till May 2025",
        seats: "5 Seats",
        rto: "Ahmedabad",
        engineDisplacement: "1498 cc",
        yearOfManufacture: "2023",
        emi: "₹28,000 /mo",
        newCarPrice: "₹13.50 Lakh",
        views: "3800+",
        badgeType: "private",
    },
    {
        id: "7",
        name: "Hyundai Creta",
        year: 2023,
        price: "₹14.80 Lakh",
        image: "/car/car7.png",
        detailOptions: [
            { label: 'Exterior', images: ['/car/car7.png', '/car/car8.png'], isActive: true },
            { label: 'Interior', images: ['/car/car9.png', '/car/car10.png'] },
            // { label: 'Highlights', images: ['/car/car8.png', '/car/car10.png'], icon: 'sparkles' },
            { label: 'Tyres', images: ['/car/car9.png', '/car/car7.png'] },
        ],
        fuelType: "Petrol",
        transmission: "Automatic",
        kmsDriven: "20,000 Kms",
        location: "Gurgaon, Haryana",
        owner: "First Owner",
        registrationYear: "2023",
        insurance: "Valid till Aug 2025",
        seats: "5 Seats",
        rto: "Gurgaon",
        engineDisplacement: "1497 cc",
        yearOfManufacture: "2023",
        emi: "₹37,000 /mo",
        newCarPrice: "₹17.20 Lakh",
        views: "5100+",
        badgeType: "assured",
    },
    {
        id: "8",
        name: "Mahindra XUV700",
        year: 2022,
        price: "₹22.50 Lakh",
        image: "/car/car8.png",
        detailOptions: [
            { label: 'Exterior', images: ['/car/car8.png', '/car/car9.png'], isActive: true },
            { label: 'Interior', images: ['/car/car10.png', '/car/car11.png'] },
            // { label: 'Highlights', images: ['/car/car9.png', '/car/car11.png'], icon: 'sparkles' },
            { label: 'Tyres', images: ['/car/car10.png', '/car/car8.png'] },
        ],
        fuelType: "Diesel",
        transmission: "Automatic",
        kmsDriven: "28,000 Kms",
        location: "Noida, Uttar Pradesh",
        owner: "First Owner",
        registrationYear: "2022",
        insurance: "Valid till Nov 2024",
        seats: "7 Seats",
        rto: "Noida",
        engineDisplacement: "2198 cc",
        yearOfManufacture: "2022",
        emi: "₹56,000 /mo",
        newCarPrice: "₹26.00 Lakh",
        views: "6700+",
        badgeType: "assured",
    },
    {
        id: "9",
        name: "Tata Nexon EV",
        year: 2023,
        price: "₹13.90 Lakh",
        image: "/car/car9.png",
        detailOptions: [
            { label: 'Exterior', images: ['/car/car9.png', '/car/car10.png'], isActive: true },
            { label: 'Interior', images: ['/car/car11.png', '/car/car12.png'] },
            // { label: 'Highlights', images: ['/car/car10.png', '/car/car12.png'], icon: 'sparkles' },
            { label: 'Tyres', images: ['/car/car11.png', '/car/car9.png'] },
        ],
        fuelType: "Electric",
        transmission: "Automatic",
        kmsDriven: "12,000 Kms",
        location: "Salt Lake, Kolkata",
        owner: "First Owner",
        registrationYear: "2023",
        insurance: "Valid till Jul 2025",
        seats: "5 Seats",
        rto: "Kolkata",
        engineDisplacement: "Electric Motor",
        yearOfManufacture: "2023",
        emi: "₹34,500 /mo",
        newCarPrice: "₹16.50 Lakh",
        views: "4400+",
        badgeType: "private",
    },
    {
        id: "10",
        name: "Maruti Swift",
        year: 2024,
        price: "₹6.20 Lakh",
        image: "/car/car10.png",
        detailOptions: [
            { label: 'Exterior', images: ['/car/car10.png', '/car/car11.png'], isActive: true },
            { label: 'Interior', images: ['/car/car12.png', '/car/car1.png'] },
            // { label: 'Highlights', images: ['/car/car11.png', '/car/car1.png'], icon: 'sparkles' },
            { label: 'Tyres', images: ['/car/car12.png', '/car/car10.png'] },
        ],
        fuelType: "Petrol",
        transmission: "Manual",
        kmsDriven: "8,000 Kms",
        location: "Vadodara, Gujarat",
        owner: "First Owner",
        registrationYear: "2024",
        insurance: "Valid till Jan 2026",
        seats: "5 Seats",
        rto: "Vadodara",
        engineDisplacement: "1197 cc",
        yearOfManufacture: "2024",
        emi: "₹15,400 /mo",
        newCarPrice: "₹7.20 Lakh",
        views: "5600+",
        badgeType: "assured",
    },
    {
        id: "11",
        name: "Ford Endeavour",
        year: 2021,
        price: "₹28.75 Lakh",
        image: "/car/car11.png",
        detailOptions: [
            { label: 'Exterior', images: ['/car/car11.png', '/car/car12.png'], isActive: true },
            { label: 'Interior', images: ['/car/car1.png', '/car/car2.png'] },
            // { label: 'Highlights', images: ['/car/car12.png', '/car/car2.png'], icon: 'sparkles' },
            { label: 'Tyres', images: ['/car/car1.png', '/car/car11.png'] },
        ],
        fuelType: "Diesel",
        transmission: "Automatic",
        kmsDriven: "35,000 Kms",
        location: "Whitefield, Bangalore",
        owner: "Second Owner",
        registrationYear: "2021",
        insurance: "Valid till Oct 2024",
        seats: "7 Seats",
        rto: "Bangalore",
        engineDisplacement: "1996 cc",
        yearOfManufacture: "2021",
        emi: "₹71,000 /mo",
        newCarPrice: "₹33.50 Lakh",
        views: "2100+",
        badgeType: "private",
    },
    {
        id: "12",
        name: "MG ZS EV",
        year: 2023,
        price: "₹17.50 Lakh",
        image: "/car/car12.png",
        detailOptions: [
            { label: 'Exterior', images: ['/car/car12.png', '/car/car1.png'], isActive: true },
            { label: 'Interior', images: ['/car/car2.png', '/car/car3.png'] },
            // { label: 'Highlights', images: ['/car/car1.png', '/car/car3.png'], icon: 'sparkles' },
            { label: 'Tyres', images: ['/car/car2.png', '/car/car12.png'] },
        ],
        fuelType: "Electric",
        transmission: "Automatic",
        kmsDriven: "16,000 Kms",
        location: "Bandra, Mumbai",
        owner: "First Owner",
        registrationYear: "2023",
        insurance: "Valid till Jun 2025",
        seats: "5 Seats",
        rto: "Mumbai",
        engineDisplacement: "Electric Motor",
        yearOfManufacture: "2023",
        emi: "₹43,400 /mo",
        newCarPrice: "₹21.00 Lakh",
        views: "3900+",
        badgeType: "assured",
    },
];

